In [3]:
import pandas as pd
data = pd.read_csv('./fish.csv')
data.head(20)

   Species  Weight  Length  Diagonal   Height   Width
0    Bream   242.0    25.4      30.0  11.5200  4.0200
1    Bream   290.0    26.3      31.2  12.4800  4.3056
2    Bream   340.0    26.5      31.1  12.3778  4.6961
3    Bream   363.0    29.0      33.5  12.7300  4.4555
4    Bream     NaN    29.0      34.0  12.4440  5.1340
5    Bream   450.0    29.7      34.7      NaN  4.9274
6    Bream   500.0    29.7      34.5  14.1795  5.2785
7    Bream   390.0    30.0       NaN      NaN  4.6900
8    Bream   450.0    30.0      35.1  14.0049  4.8438
9    Bream   500.0     NaN      36.2  14.2266  4.9594
10   Bream   475.0     NaN       NaN      NaN     NaN
11   Bream   500.0    31.0      36.2  14.3714  4.8146
12   Bream     NaN    31.5      36.4  13.7592  4.3680
13   Bream   340.0    32.0      37.3  13.9129  5.0728
14   Bream   600.0    32.0      37.2  14.9544  5.1708
15   Bream   600.0    32.0      37.2  15.4380  5.5800
16   Bream   700.0    33.0      38.3  14.8604  5.2854
17   Bream   700.0    33.0      38.5  14.9380  5.1975
18   Bream   610.0    33.5      38.6      NaN  5.1338
19   Bream   650.0    33.5      38.7  14.4738  5.7276